### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by urish** [debug-edge/debug-edge.github.io#2]
The website says:

> This is all theoretical at this point. It is untested! We have sample boards and connectors ordered. We have not tried it in practice yet. That means we're open to feedback! Please post an issue on one of our GitHub repos with your thoughts. Thanks!

I see that it was last updated 10 months ago. Have the connectors been tested since?

**Comment by tannewt** [comment]
I've used it a little myself, not day to day. The connector are pretty stiff but work solidly.

**Comment by urish** [comment]
Thanks Scott! Would you use it for your next project?

**Comment by tannewt** [comment]
Ya, I would if I had the edge space and it was routable.

**Comment by urish** [comment]
Thank you! Any alternatives you'd consider?

Currently using SOICbite - overall it's a nice solution, but you need to manually file the clips

**Comment by tannewt** [comment]
Not on the edge. If I didn't have edge space then I'd do a standard 2x5 footprint but that requires additional soldering to use. Overall, I'd use debug edge if I had the space.

**Comment by urish** [comment]
Got it, thanks a bunch for sharing your thoughts!

**Comment by oswinrodrigues** [comment]
Hi, I'd just like to inquire about this again. Since July 2021, have there been any updates regarding the robustness of this solution from more testing or projects that have used it? Thanks!
